# Site settings
title: Boom Blog
description: Aheri's Amazing Adventures becoming a Software Engineer
keywords: Javascript, Bootcamp, 
author: Aheri aka MachTech
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://machtech.github.io" # the base hostname & protocol for your site
